django_apis/accounts/urls.py
from django.conf.urls import url
from .views import UserProfileDetailView

urlpatterns = [
    url(r'^profile/$', UserProfileDetailView.as_view(), name='user_profile'),
]

django_apis/common/urls.py
from django.conf.urls import url
from .views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

django_apis/config/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'django_apis.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
)

django_apis/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import uuid
import os

# Create your models here.


def get_file_path(instance, filename):
    """
    Helper function to provide user profile images an unique filename
    to avoid overwrites
    """
    file_extension = filename.split('.')[-1]
    filename = "{file_name}.{file_extension}".format(
        file_name=uuid.uuid4(), file_extension=file_extension
    )
    path = os.path.join('accounts/user_profile', filename)
    return path


class UserProfile(models.Model):
    """
        Model to handle user profile information and extend
        the functionality of the basic Django User model and its fields
    """

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    GENDER_CHOICES = [
        ('Male', _('Male')),
        ('Female', _('Female'))
    ]

    authentication_user = models.OneToOneField(User)
    age = models.PositiveSmallIntegerField(
        _('User age'),
        null=True,
        blank=True,
        help_text=_('Write an age for the user profile')
    )
    gender = models.CharField(
        _('User gender'),
        max_length=6,
        choices=GENDER_CHOICES,
        blank=True,
        help_text=_('Select a gender for the user profile')
    )
    image_profile = models.ImageField(
        _('User image profile'),
        blank=True,
        upload_to=get_file_path,
        default='{url}{image_path}'.format(
            url=settings.STATIC_URL,
            image_path='accounts/img/profile-photo.png'
        ),
        help_text=_('Upload an image for the user profile')
    )

    def __unicode__(self):
        return '{first_name} {last_name}'.format(
            first_name=self.authentication_user.first_name,
            last_name=self.authentication_user.last_name)

django_apis/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name'
        ]

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def signup(self, request, user):
        user.save()
        UserProfile.objects.create(authentication_user=user)

django_apis/accounts/views.py
from django.views.generic import DetailView
from common.mixins import LoginRequiredMixin
from .models import UserProfile
# Create your views here.


class UserProfileDetailView(LoginRequiredMixin, DetailView):
        template_name = 'account/user_profile.html'
        context_object_name = 'user_profile'

        def get_object(self, queryset=None):
            authentication_user = self.request.user
            user, created = UserProfile.objects.get_or_create(
                authentication_user=authentication_user
            )
            return user

        def get_context_data(self, **kwargs):
            context = super(UserProfileDetailView, self).get_context_data(
                **kwargs
            )
            user = self.request.user
            context['user_accounts'] = user.socialaccount_set.all()
            return context

django_apis/common/views.py
from django.views.generic import TemplateView
# Create your views here.


class IndexView(TemplateView):
    template_name = 'common/index.html'

django_apis/templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}BarApp{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'common/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/common.css' %}">
        <script src="{% static 'common/js/vendor/modernizr.min.js' %}"></script>
        {% block extra-head-tags %}{% endblock %}
    </head>
    <body>

        {% include 'navigation_bar.html' %}

        <!--[if lt IE 8]>
            <div class="container">
                <div class="alert alert-info" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                    Estás usando un <strong>navegador antiguo</strong>. Por favor, <a href="http://browsehappy.com/">actualizalo</a> para mejorar tu experiencia.
                </div>
            </div>
        <![endif]-->

        {% include 'messages.html' %}

        {% block content %}{% endblock %}

        <script src="{% static 'common/js/vendor/jquery.min.js' %}"></script>
        <script src="{% static 'common/js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'common/js/plugins.js' %}"></script>
        {% block extra-script-tags %}{% endblock %}
    </body>
</html>

django_apis/templates/common/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <div class="container">
            <h1>{% trans "Welcome!" %}</h1>
            <p>{% trans "Django project to retrieve user profile information from different social APIs!!" %}</p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'account_signup' %}" role="button">{% trans "Register" %}</a></p>
        </div><!-- container -->
    </div><!-- jumbotron -->
</div><!-- container -->

{% endblock %}

django_apis/templates/messages.html
{% if messages %}
<div class="container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {{ message }}
    </div><!-- alert -->
    {% endfor %}
</div><!-- container -->
{% endif %}

django_apis/templates/navigation_bar.html
{% load i18n %}
<div id="navigation-bar" class="container">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button><!-- navbar-toggle -->
            <a class="navbar-brand" href="{% url 'common:index' %}">Social APIS</a>
        </div><!-- navbar-header -->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'common:index' %}">{% trans "Home" %}</a>
                </li>
            </ul><!-- navbar-nav -->
            <ul class="nav navbar-nav navbar-right">
                
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ user.get_full_name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">

                        <li>
                            <a href="{% url 'accounts:user_profile' %}">{% trans "Profile" %}</a>
                        </li>      
                        <li>
                            <a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                        </li>
                    </ul><!-- dropdown-menu -->
                </li><!-- dropdown -->
                {% else %}
                <li>
                    <a href="{% url 'account_login' %}">{% trans "Login" %}</a>
                </li>
                <li>
                    <a href="{% url 'account_signup' %}">{% trans "Register" %}</a>
                </li>
                {% endif %}
            </ul><!-- navbar-nav -->
        </div><!-- nav-collapse -->
    </div><!-- navbar -->
</div><!-- container -->